[2023-12-15T08:24:17.554+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snow_pipeline.data_loading_table2 manual__2023-12-15T08:24:00.730109+00:00 [queued]>
[2023-12-15T08:24:17.568+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snow_pipeline.data_loading_table2 manual__2023-12-15T08:24:00.730109+00:00 [queued]>
[2023-12-15T08:24:17.569+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 3
[2023-12-15T08:24:17.584+0000] {taskinstance.py:1382} INFO - Executing <Task(SnowflakeOperator): data_loading_table2> on 2023-12-15 08:24:00.730109+00:00
[2023-12-15T08:24:17.591+0000] {standard_task_runner.py:57} INFO - Started process 1435 to run task
[2023-12-15T08:24:17.595+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'snow_pipeline', 'data_loading_table2', 'manual__2023-12-15T08:24:00.730109+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_dag.py', '--cfg-path', '/tmp/tmpmryphoe0']
[2023-12-15T08:24:17.606+0000] {standard_task_runner.py:85} INFO - Job 239: Subtask data_loading_table2
[2023-12-15T08:24:17.686+0000] {task_command.py:416} INFO - Running <TaskInstance: snow_pipeline.data_loading_table2 manual__2023-12-15T08:24:00.730109+00:00 [running]> on host e65e9d73b232
[2023-12-15T08:24:17.779+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarthak' AIRFLOW_CTX_DAG_ID='snow_pipeline' AIRFLOW_CTX_TASK_ID='data_loading_table2' AIRFLOW_CTX_EXECUTION_DATE='2023-12-15T08:24:00.730109+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-15T08:24:00.730109+00:00'
[2023-12-15T08:24:17.780+0000] {sql.py:274} INFO - Executing: 
insert into DEMO_DB2.DEMO_SCHEMA.webpage_sales2(webpage_sk,orderno,qty,net_profit)
select WS_WEB_PAGE_SK,WS_ORDER_NUMBER,WS_QUANTITY,WS_NET_PROFIT from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SALES
limit 50000;
[2023-12-15T08:24:17.789+0000] {base.py:73} INFO - Using connection ID 'snowflake_2' for task execution.
[2023-12-15T08:24:17.796+0000] {base.py:73} INFO - Using connection ID 'snowflake_2' for task execution.
[2023-12-15T08:24:17.798+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.5.11-linuxkit-aarch64-with-glibc2.17
[2023-12-15T08:24:17.801+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-12-15T08:24:17.801+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2023-12-15T08:24:18.342+0000] {cursor.py:833} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-12-15T08:24:18.443+0000] {cursor.py:846} INFO - query execution done
[2023-12-15T08:24:18.444+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-15T08:24:18.445+0000] {sql.py:418} INFO - Running statement: insert into DEMO_DB2.DEMO_SCHEMA.webpage_sales2(webpage_sk,orderno,qty,net_profit)
select WS_WEB_PAGE_SK,WS_ORDER_NUMBER,WS_QUANTITY,WS_NET_PROFIT from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SALES
limit 50000;, parameters: None
[2023-12-15T08:24:18.445+0000] {cursor.py:833} INFO - query: [insert into DEMO_DB2.DEMO_SCHEMA.webpage_sales2(webpage_sk,orderno,qty,net_profi...]
[2023-12-15T08:24:18.566+0000] {cursor.py:846} INFO - query execution done
[2023-12-15T08:24:18.581+0000] {connection.py:677} INFO - closed
[2023-12-15T08:24:18.652+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2023-12-15T08:24:18.731+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 937, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01b10038-3200-f715-0007-444200023496: SQL compilation error:
Table 'DEMO_DB2.DEMO_SCHEMA.WEBPAGE_SALES2' does not exist or not authorized.
[2023-12-15T08:24:18.754+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=snow_pipeline, task_id=data_loading_table2, execution_date=20231215T082400, start_date=20231215T082417, end_date=20231215T082418
[2023-12-15T08:24:18.775+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 239 for task data_loading_table2 (002003 (42S02): 01b10038-3200-f715-0007-444200023496: SQL compilation error:
Table 'DEMO_DB2.DEMO_SCHEMA.WEBPAGE_SALES2' does not exist or not authorized.; 1435)
[2023-12-15T08:24:18.800+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T08:24:18.820+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
