[2023-12-12T07:03:15.688+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.copy_into_command scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-12T07:03:15.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.copy_into_command scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-12T07:03:15.697+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-12T07:03:15.707+0000] {taskinstance.py:1382} INFO - Executing <Task(SnowflakeOperator): copy_into_command> on 2023-12-11 00:00:00+00:00
[2023-12-12T07:03:15.712+0000] {standard_task_runner.py:57} INFO - Started process 619 to run task
[2023-12-12T07:03:15.718+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'copy_into_command', 'scheduled__2023-12-11T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_dag.py', '--cfg-path', '/tmp/tmp8fohwohf']
[2023-12-12T07:03:15.722+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask copy_into_command
[2023-12-12T07:03:15.754+0000] {task_command.py:416} INFO - Running <TaskInstance: pipeline.copy_into_command scheduled__2023-12-11T00:00:00+00:00 [running]> on host d50382fa2a13
[2023-12-12T07:03:15.795+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarthak' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='copy_into_command' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:00:00+00:00'
[2023-12-12T07:03:15.796+0000] {sql.py:274} INFO - Executing: COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,Founded,Industry,Number_of_employees)
FROM @my_s3_stage
FILE_FORMAT = (FORMAT_NAME = my_csv_format)
ON_ERROR=CONTINUE 
[2023-12-12T07:03:15.802+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-12-12T07:03:15.809+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-12-12T07:03:15.809+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.5.11-linuxkit-aarch64-with-glibc2.17
[2023-12-12T07:03:15.810+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-12-12T07:03:15.810+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2023-12-12T07:03:16.753+0000] {cursor.py:833} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-12-12T07:03:16.868+0000] {cursor.py:846} INFO - query execution done
[2023-12-12T07:03:16.870+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-12T07:03:16.871+0000] {sql.py:418} INFO - Running statement: COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,Founded,Industry,Number_of_employees)
FROM @my_s3_stage
FILE_FORMAT = (FORMAT_NAME = my_csv_format)
ON_ERROR=CONTINUE, parameters: None
[2023-12-12T07:03:16.872+0000] {cursor.py:833} INFO - query: [COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,...]
[2023-12-12T07:03:22.281+0000] {cursor.py:846} INFO - query execution done
[2023-12-12T07:03:22.281+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-12T07:03:22.282+0000] {sql.py:427} INFO - Rows affected: 1
[2023-12-12T07:03:22.282+0000] {snowflake.py:400} INFO - Rows affected: 1
[2023-12-12T07:03:22.282+0000] {snowflake.py:401} INFO - Snowflake query id: 01b0ef07-3200-f5e3-0000-00074442e0e9
[2023-12-12T07:03:22.282+0000] {cursor.py:833} INFO - query: [COMMIT]
[2023-12-12T07:03:22.586+0000] {cursor.py:846} INFO - query execution done
[2023-12-12T07:03:22.587+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-12T07:03:22.587+0000] {connection.py:677} INFO - closed
[2023-12-12T07:03:22.653+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2023-12-12T07:03:22.740+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=copy_into_command, execution_date=20231211T000000, start_date=20231212T070315, end_date=20231212T070322
[2023-12-12T07:03:22.768+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-12T07:03:22.776+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
