[2023-12-10T18:58:24.496+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:24.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T18:58:24.498+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:24.498+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:24.506+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:24.504+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T18:58:24.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:24.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.040 seconds
[2023-12-10T18:58:54.812+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:54.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T18:58:54.817+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:54.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:54.825+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:54.823+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T18:58:54.825+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:58:54.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.049 seconds
[2023-12-10T18:59:25.105+0000] {processor.py:157} INFO - Started process (PID=262) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:25.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T18:59:25.108+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:25.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:25.116+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:25.114+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T18:59:25.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:25.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.036 seconds
[2023-12-10T18:59:55.444+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:55.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T18:59:55.447+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:55.447+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:55.475+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:55.468+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T18:59:55.476+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T18:59:55.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.059 seconds
[2023-12-10T19:00:25.795+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:25.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:00:25.799+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:25.798+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:25.807+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:25.805+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:00:25.807+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:25.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.038 seconds
[2023-12-10T19:00:56.129+0000] {processor.py:157} INFO - Started process (PID=298) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:56.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:00:56.133+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:56.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:56.142+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:56.140+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:00:56.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:00:56.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.041 seconds
[2023-12-10T19:01:26.424+0000] {processor.py:157} INFO - Started process (PID=310) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:26.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:01:26.429+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:26.428+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:26.437+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:26.435+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:01:26.437+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:26.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:01:50.696+0000] {processor.py:157} INFO - Started process (PID=322) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:50.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:01:50.701+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:50.700+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:50.721+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:50.719+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:01:50.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:01:50.746+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.064 seconds
[2023-12-10T19:02:20.976+0000] {processor.py:157} INFO - Started process (PID=333) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:20.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:02:20.978+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:20.978+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:20.983+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:20.982+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:02:20.984+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:20.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.024 seconds
[2023-12-10T19:02:51.321+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:51.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:02:51.324+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:51.324+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:51.333+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:51.331+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:02:51.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:02:51.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:03:21.580+0000] {processor.py:157} INFO - Started process (PID=357) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:21.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:03:21.583+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:03:21.582+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:21.586+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:03:21.585+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:03:21.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:21.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.021 seconds
[2023-12-10T19:03:51.895+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:51.897+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:03:51.898+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:03:51.897+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:51.905+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:03:51.903+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:03:51.906+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:03:51.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.034 seconds
[2023-12-10T19:04:22.152+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:22.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:04:22.155+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:04:22.154+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:22.163+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:04:22.162+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:04:22.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:22.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.038 seconds
[2023-12-10T19:04:52.388+0000] {processor.py:157} INFO - Started process (PID=393) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:52.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:04:52.391+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:04:52.391+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:52.397+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:04:52.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:04:52.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:04:52.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.035 seconds
[2023-12-10T19:05:22.653+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:22.654+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:05:22.656+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:05:22.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:22.664+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:05:22.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:05:22.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:22.683+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:05:52.901+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:52.903+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:05:52.904+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:05:52.904+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:52.911+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:05:52.909+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:05:52.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:05:52.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.033 seconds
[2023-12-10T19:06:23.167+0000] {processor.py:157} INFO - Started process (PID=429) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:23.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:06:23.169+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:06:23.169+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:23.176+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:06:23.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:06:23.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:23.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.032 seconds
[2023-12-10T19:06:53.438+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:53.439+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:06:53.440+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:06:53.440+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:53.447+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:06:53.445+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:06:53.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:06:53.463+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.029 seconds
[2023-12-10T19:07:23.642+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:23.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:07:23.646+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:07:23.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:23.652+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:07:23.650+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:07:23.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:23.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.031 seconds
[2023-12-10T19:07:53.942+0000] {processor.py:157} INFO - Started process (PID=488) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:53.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:07:53.948+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:07:53.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:53.964+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:07:53.962+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:07:53.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:07:53.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.047 seconds
[2023-12-10T19:08:24.269+0000] {processor.py:157} INFO - Started process (PID=509) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:24.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:08:24.273+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:08:24.272+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:24.285+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:08:24.280+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:08:24.286+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:24.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.066 seconds
[2023-12-10T19:08:54.609+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:54.613+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:08:54.615+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:08:54.614+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:54.624+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:08:54.622+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:08:54.625+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:08:54.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.042 seconds
[2023-12-10T19:09:24.879+0000] {processor.py:157} INFO - Started process (PID=550) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:24.881+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:09:24.882+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:09:24.881+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:24.889+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:09:24.887+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:09:24.889+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:24.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.032 seconds
[2023-12-10T19:09:55.146+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:55.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:09:55.149+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:09:55.148+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:55.156+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:09:55.154+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:09:55.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:09:55.181+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.040 seconds
[2023-12-10T19:10:25.465+0000] {processor.py:157} INFO - Started process (PID=575) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:25.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:10:25.468+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:10:25.468+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:25.476+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:10:25.474+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:10:25.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:25.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.040 seconds
[2023-12-10T19:10:55.795+0000] {processor.py:157} INFO - Started process (PID=587) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:55.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:10:55.798+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:10:55.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:55.804+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:10:55.802+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:10:55.805+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:10:55.823+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.033 seconds
[2023-12-10T19:11:26.051+0000] {processor.py:157} INFO - Started process (PID=599) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:26.052+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:11:26.053+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:26.053+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:26.061+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:26.059+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:11:26.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:26.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:11:56.343+0000] {processor.py:157} INFO - Started process (PID=611) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:56.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:11:56.347+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:56.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:56.355+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:56.353+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:11:56.356+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:56.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.039 seconds
[2023-12-10T19:11:59.377+0000] {processor.py:157} INFO - Started process (PID=616) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:59.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:11:59.380+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:59.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:59.389+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:11:59.388+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:11:59.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:11:59.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.036 seconds
[2023-12-10T19:12:29.673+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:12:29.676+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:12:29.677+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:12:29.677+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:12:29.686+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:12:29.684+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:12:29.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:12:29.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.040 seconds
[2023-12-10T19:12:59.957+0000] {processor.py:157} INFO - Started process (PID=640) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:12:59.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:12:59.961+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:12:59.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:12:59.983+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:12:59.980+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:12:59.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:13:00.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.051 seconds
[2023-12-10T19:13:30.249+0000] {processor.py:157} INFO - Started process (PID=652) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:13:30.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:13:30.257+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:13:30.255+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:13:30.271+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:13:30.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:13:30.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:13:30.289+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.044 seconds
[2023-12-10T19:14:29.028+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:29.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:14:29.029+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:14:29.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:29.033+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:14:29.032+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:14:29.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:29.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.022 seconds
[2023-12-10T19:14:59.278+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:59.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:14:59.281+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:14:59.281+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:59.288+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:14:59.287+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:14:59.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:14:59.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.032 seconds
[2023-12-10T19:15:29.521+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:29.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:15:29.523+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:15:29.523+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:29.531+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:15:29.529+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:15:29.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:29.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.033 seconds
[2023-12-10T19:15:59.748+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:59.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:15:59.751+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:15:59.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:59.759+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:15:59.757+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:15:59.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:15:59.778+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.035 seconds
[2023-12-10T19:16:29.977+0000] {processor.py:157} INFO - Started process (PID=216) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:16:29.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:16:29.980+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:16:29.980+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:16:29.988+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:16:29.986+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:16:29.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:16:30.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.033 seconds
[2023-12-10T19:17:00.222+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:00.224+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:17:00.225+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:17:00.224+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:00.233+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:17:00.231+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:17:00.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:00.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.040 seconds
[2023-12-10T19:17:30.502+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:30.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:17:30.504+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:17:30.504+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:30.508+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:17:30.507+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:17:30.509+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:17:30.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.025 seconds
[2023-12-10T19:18:00.815+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:00.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:18:00.817+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:18:00.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:00.824+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:18:00.822+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:18:00.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:00.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.036 seconds
[2023-12-10T19:18:31.143+0000] {processor.py:157} INFO - Started process (PID=264) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:31.144+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:18:31.145+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:18:31.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:31.153+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:18:31.151+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:18:31.153+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:18:31.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.039 seconds
[2023-12-10T19:19:01.412+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:01.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:19:01.415+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:19:01.414+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:01.435+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:19:01.422+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:19:01.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:01.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.069 seconds
[2023-12-10T19:19:31.742+0000] {processor.py:157} INFO - Started process (PID=288) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:31.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:19:31.745+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:19:31.744+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:31.754+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:19:31.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:19:31.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:19:31.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.041 seconds
[2023-12-10T19:20:02.068+0000] {processor.py:157} INFO - Started process (PID=300) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:02.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:20:02.071+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:20:02.070+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:02.078+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:20:02.076+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:20:02.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:02.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.041 seconds
[2023-12-10T19:20:32.386+0000] {processor.py:157} INFO - Started process (PID=312) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:32.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:20:32.389+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:20:32.389+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:32.398+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:20:32.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:20:32.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:20:32.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.046 seconds
[2023-12-10T19:21:02.676+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:02.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:21:02.678+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:21:02.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:02.684+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:21:02.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:21:02.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:02.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.032 seconds
[2023-12-10T19:21:32.998+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:32.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:21:33.000+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:21:33.000+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:33.007+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:21:33.005+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:21:33.008+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:21:33.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.042 seconds
[2023-12-10T19:22:03.263+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:03.265+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:22:03.267+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:03.266+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:03.294+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:03.285+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:22:03.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:03.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.070 seconds
[2023-12-10T19:22:33.546+0000] {processor.py:157} INFO - Started process (PID=359) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:33.548+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:22:33.550+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:33.549+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:33.556+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:33.555+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:22:33.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:22:33.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.038 seconds
[2023-12-10T19:23:03.811+0000] {processor.py:157} INFO - Started process (PID=371) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:03.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:23:03.813+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:03.813+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:03.820+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:03.818+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:23:03.821+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:03.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.046 seconds
[2023-12-10T19:23:34.098+0000] {processor.py:157} INFO - Started process (PID=383) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:34.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:23:34.101+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:34.101+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:34.112+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:34.109+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:23:34.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:23:34.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.047 seconds
[2023-12-10T19:24:04.381+0000] {processor.py:157} INFO - Started process (PID=395) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:04.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:24:04.383+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:04.383+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:04.402+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:04.396+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:24:04.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:04.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.064 seconds
[2023-12-10T19:24:34.704+0000] {processor.py:157} INFO - Started process (PID=407) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:34.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:24:34.706+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:34.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:34.720+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:34.712+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:24:34.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:24:34.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.055 seconds
[2023-12-10T19:25:05.021+0000] {processor.py:157} INFO - Started process (PID=419) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:05.023+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:25:05.024+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:05.023+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:05.030+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:05.028+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:25:05.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:05.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.039 seconds
[2023-12-10T19:25:35.277+0000] {processor.py:157} INFO - Started process (PID=431) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:35.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:25:35.280+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:35.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:35.286+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:35.285+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:25:35.287+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:25:35.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.036 seconds
[2023-12-10T19:26:05.626+0000] {processor.py:157} INFO - Started process (PID=443) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:05.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:26:05.630+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:26:05.629+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:05.638+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:26:05.636+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:26:05.638+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:05.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.056 seconds
[2023-12-10T19:26:35.925+0000] {processor.py:157} INFO - Started process (PID=455) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:35.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:26:35.928+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:26:35.928+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:35.935+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:26:35.934+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:26:35.936+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:26:35.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.036 seconds
[2023-12-10T19:27:06.234+0000] {processor.py:157} INFO - Started process (PID=467) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:06.236+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:27:06.237+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:06.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:06.246+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:06.244+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2023-12-10T19:27:06.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:06.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.034 seconds
[2023-12-10T19:27:14.368+0000] {processor.py:157} INFO - Started process (PID=472) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:14.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:27:14.371+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:14.370+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:14.379+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:14.378+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:27:14.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:14.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.039 seconds
[2023-12-10T19:27:15.408+0000] {processor.py:157} INFO - Started process (PID=477) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:15.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:27:15.410+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:15.410+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:15.417+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:15.415+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:27:15.417+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:15.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:27:45.701+0000] {processor.py:157} INFO - Started process (PID=488) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:45.702+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:27:45.704+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:45.703+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:45.711+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:27:45.709+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:27:45.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:27:45.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.034 seconds
[2023-12-10T19:28:15.935+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:15.937+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:28:15.938+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:28:15.938+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:15.945+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:28:15.943+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:28:15.946+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:15.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.034 seconds
[2023-12-10T19:28:46.272+0000] {processor.py:157} INFO - Started process (PID=512) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:46.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:28:46.275+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:28:46.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:46.282+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:28:46.280+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:28:46.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:28:46.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:29:16.585+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:16.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:29:16.589+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:29:16.588+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:16.596+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:29:16.594+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:29:16.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:16.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:29:46.913+0000] {processor.py:157} INFO - Started process (PID=536) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:46.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:29:46.917+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:29:46.916+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:46.924+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:29:46.922+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:29:46.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:29:46.943+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:30:17.344+0000] {processor.py:157} INFO - Started process (PID=548) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:17.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:30:17.347+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:30:17.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:17.353+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:30:17.352+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:30:17.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:17.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.049 seconds
[2023-12-10T19:30:47.677+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:47.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:30:47.681+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:30:47.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:47.687+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:30:47.685+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/s3_upload_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_upload_dag.py", line 3, in <module>
    from airflow.operators.python import PyhonOperator
ImportError: cannot import name 'PyhonOperator' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py)
[2023-12-10T19:30:47.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:30:47.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.037 seconds
[2023-12-10T19:31:05.929+0000] {processor.py:157} INFO - Started process (PID=572) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:05.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:31:05.937+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:05.935+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:06.223+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:06.398+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.398+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-10T19:31:06.406+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.405+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-10T19:31:06.410+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.409+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-12-10T19:31:06.410+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.410+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:31:06.418+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.418+0000] {dag.py:2963} INFO - Creating ORM DAG for s3_upload
[2023-12-10T19:31:06.427+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:06.427+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:31:06.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.531 seconds
[2023-12-10T19:31:36.817+0000] {processor.py:157} INFO - Started process (PID=583) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:36.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:31:36.822+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:36.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:36.893+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:31:36.914+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:36.914+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:31:36.941+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:31:36.941+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:31:36.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.143 seconds
[2023-12-10T19:32:07.143+0000] {processor.py:157} INFO - Started process (PID=595) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:07.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:32:07.152+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:07.150+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:07.218+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:07.259+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:07.259+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:32:07.277+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:07.277+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:32:07.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.165 seconds
[2023-12-10T19:32:37.485+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:37.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:32:37.489+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:37.488+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:37.579+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:32:37.609+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:37.609+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:32:37.626+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:32:37.626+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:32:37.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.159 seconds
[2023-12-10T19:33:07.840+0000] {processor.py:157} INFO - Started process (PID=619) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:07.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:33:07.845+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:07.844+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:07.933+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:07.956+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:07.956+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:33:07.973+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:07.973+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:33:07.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.153 seconds
[2023-12-10T19:33:38.174+0000] {processor.py:157} INFO - Started process (PID=631) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:38.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:33:38.178+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:38.178+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:38.263+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:33:38.287+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:38.286+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:33:38.302+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:33:38.302+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:33:38.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.144 seconds
[2023-12-10T19:34:08.536+0000] {processor.py:157} INFO - Started process (PID=643) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:08.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:34:08.539+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:08.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:08.616+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:08.651+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:08.651+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:34:08.666+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:08.666+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:34:08.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.145 seconds
[2023-12-10T19:34:38.801+0000] {processor.py:157} INFO - Started process (PID=655) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:38.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:34:38.805+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:38.805+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:38.875+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:34:38.910+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:38.910+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:34:38.928+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:34:38.927+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:34:38.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.144 seconds
[2023-12-10T19:35:09.240+0000] {processor.py:157} INFO - Started process (PID=667) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:09.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:35:09.245+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:09.244+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:09.321+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:09.342+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:09.342+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:35:09.357+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:09.357+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:35:09.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.133 seconds
[2023-12-10T19:35:39.542+0000] {processor.py:157} INFO - Started process (PID=679) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:39.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:35:39.546+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:39.545+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:39.668+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:35:39.688+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:39.688+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:35:39.703+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:35:39.703+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:35:39.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.177 seconds
[2023-12-10T19:36:10.010+0000] {processor.py:157} INFO - Started process (PID=691) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:10.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:36:10.013+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:10.012+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:10.076+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:10.098+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:10.098+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:36:10.113+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:10.113+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:36:10.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.117 seconds
[2023-12-10T19:36:35.354+0000] {processor.py:157} INFO - Started process (PID=702) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:35.355+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:36:35.356+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:35.356+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:35.432+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:36:35.454+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:35.454+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:36:35.479+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:36:35.478+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:36:35.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.143 seconds
[2023-12-10T19:37:05.617+0000] {processor.py:157} INFO - Started process (PID=714) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:05.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:37:05.621+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:05.620+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:05.695+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:05.717+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:05.717+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:37:05.732+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:05.732+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:37:05.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.132 seconds
[2023-12-10T19:37:36.033+0000] {processor.py:157} INFO - Started process (PID=729) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:36.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:37:36.036+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:36.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:36.101+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:37:36.119+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:36.119+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:37:36.133+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:37:36.133+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:37:36.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.116 seconds
[2023-12-10T19:38:06.373+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:06.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:38:06.376+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:06.375+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:06.473+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:06.493+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:06.493+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:38:06.508+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:06.508+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:38:06.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.150 seconds
[2023-12-10T19:38:36.651+0000] {processor.py:157} INFO - Started process (PID=752) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:36.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:38:36.653+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:36.653+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:36.742+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:36.764+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:36.764+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:38:36.780+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:36.780+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:38:36.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.143 seconds
[2023-12-10T19:38:59.910+0000] {processor.py:157} INFO - Started process (PID=764) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:59.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:38:59.915+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:38:59.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:38:59.986+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:39:00.060+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:39:00.059+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:39:00.070+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:39:00.070+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:39:00.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.175 seconds
[2023-12-10T19:39:30.200+0000] {processor.py:157} INFO - Started process (PID=784) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:39:30.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:39:30.202+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:39:30.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:39:30.247+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:39:30.261+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:39:30.261+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:39:30.280+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:39:30.280+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:39:30.289+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.091 seconds
[2023-12-10T19:40:00.490+0000] {processor.py:157} INFO - Started process (PID=799) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:00.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:40:00.493+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:00.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:00.585+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:00.609+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:00.608+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:40:00.623+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:00.623+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:40:00.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.147 seconds
[2023-12-10T19:40:30.787+0000] {processor.py:157} INFO - Started process (PID=814) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:30.790+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:40:30.791+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:30.791+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:30.882+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:40:30.901+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:30.901+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:40:30.916+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:40:30.916+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:40:30.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.145 seconds
[2023-12-10T19:41:01.234+0000] {processor.py:157} INFO - Started process (PID=826) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:01.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:41:01.236+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:01.236+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:01.300+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:01.320+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:01.320+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:41:01.334+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:01.334+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:41:01.343+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.115 seconds
[2023-12-10T19:41:31.490+0000] {processor.py:157} INFO - Started process (PID=838) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:31.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:41:31.492+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:31.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:31.551+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:41:31.563+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:31.563+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:41:31.575+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:41:31.574+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:41:31.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.098 seconds
[2023-12-10T19:42:01.857+0000] {processor.py:157} INFO - Started process (PID=850) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:01.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:42:01.861+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:01.861+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:01.954+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:01.978+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:01.978+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:42:01.994+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:01.994+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:42:02.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.153 seconds
[2023-12-10T19:42:32.170+0000] {processor.py:157} INFO - Started process (PID=862) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:32.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:42:32.174+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:32.173+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:32.244+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:42:32.263+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:32.263+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:42:32.278+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:42:32.278+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:42:32.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.125 seconds
[2023-12-10T19:43:02.573+0000] {processor.py:157} INFO - Started process (PID=874) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:02.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:43:02.576+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:02.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:02.653+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:02.673+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:02.673+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:43:02.688+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:02.688+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:43:02.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.131 seconds
[2023-12-10T19:43:08.622+0000] {processor.py:157} INFO - Started process (PID=879) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:08.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:43:08.623+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:08.623+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:08.679+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:08.744+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:08.744+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:43:08.756+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:08.755+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:43:08.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.149 seconds
[2023-12-10T19:43:09.778+0000] {processor.py:157} INFO - Started process (PID=884) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:09.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:43:09.781+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:09.780+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:09.847+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:09.855+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:09.855+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:43:09.867+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:09.867+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:43:09.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.106 seconds
[2023-12-10T19:43:40.089+0000] {processor.py:157} INFO - Started process (PID=899) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:40.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:43:40.092+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:40.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:40.139+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:43:40.157+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:40.156+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:43:40.171+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:43:40.171+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:43:40.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.096 seconds
[2023-12-10T19:44:10.398+0000] {processor.py:157} INFO - Started process (PID=917) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:10.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:44:10.399+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:10.399+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:10.445+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:10.460+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:10.460+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:44:10.472+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:10.472+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:44:10.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.086 seconds
[2023-12-10T19:44:40.698+0000] {processor.py:157} INFO - Started process (PID=932) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:40.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:44:40.703+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:40.701+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:40.787+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:44:40.808+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:40.808+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:44:40.823+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:44:40.823+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:44:40.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.141 seconds
[2023-12-10T19:45:16.893+0000] {processor.py:157} INFO - Started process (PID=944) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:45:16.896+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:45:16.898+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:45:16.897+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:45:16.982+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:45:17.005+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:45:17.005+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:45:17.023+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:45:17.022+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:45:17.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.150 seconds
[2023-12-10T19:46:11.360+0000] {processor.py:157} INFO - Started process (PID=956) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:46:11.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T19:46:11.365+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:46:11.364+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:46:11.450+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T19:46:11.496+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:46:11.495+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T19:46:11.514+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:46:11.514+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T19:46:11.524+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.186 seconds
[2023-12-10T20:28:09.881+0000] {processor.py:157} INFO - Started process (PID=972) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T20:28:09.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T20:28:09.888+0000] {logging_mixin.py:154} INFO - [2023-12-10T20:28:09.887+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T20:28:10.066+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T20:28:10.121+0000] {logging_mixin.py:154} INFO - [2023-12-10T20:28:10.121+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T20:28:10.146+0000] {logging_mixin.py:154} INFO - [2023-12-10T20:28:10.146+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T20:28:10.158+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.287 seconds
[2023-12-10T21:45:53.523+0000] {processor.py:157} INFO - Started process (PID=984) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T21:45:53.524+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T21:45:53.525+0000] {logging_mixin.py:154} INFO - [2023-12-10T21:45:53.525+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T21:45:53.599+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T21:45:53.630+0000] {logging_mixin.py:154} INFO - [2023-12-10T21:45:53.630+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T21:45:53.657+0000] {logging_mixin.py:154} INFO - [2023-12-10T21:45:53.657+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T21:45:53.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.154 seconds
[2023-12-10T23:10:06.131+0000] {processor.py:157} INFO - Started process (PID=996) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:06.133+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T23:10:06.135+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:06.134+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:06.253+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:06.272+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:06.272+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T23:10:06.287+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:06.287+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T23:10:06.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.188 seconds
[2023-12-10T23:10:37.266+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:37.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/s3_upload_dag.py for tasks to queue
[2023-12-10T23:10:37.273+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:37.273+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:37.487+0000] {processor.py:839} INFO - DAG(s) dict_keys(['s3_upload']) retrieved from /opt/airflow/dags/s3_upload_dag.py
[2023-12-10T23:10:37.568+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:37.568+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-10T23:10:37.621+0000] {logging_mixin.py:154} INFO - [2023-12-10T23:10:37.621+0000] {dag.py:3722} INFO - Setting next_dagrun for s3_upload to 2023-12-10T00:00:00+00:00, run_after=2023-12-11T00:00:00+00:00
[2023-12-10T23:10:37.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/s3_upload_dag.py took 0.401 seconds
